SET SCHEMA DB2SAMPLE;
CREATE FUNCTION FN_45546_GETP(inputNumber CHAR(6))
RETURNS TABLE
  (NAME VARCHAR(12),
   LNAME VARCHAR(15),
   WORKDEPT CHAR(3),
   WORKDATE INT)
SPECIFIC FN_45546_GETP
RETURN
    SELECT E.FIRSTNME, E.LASTNAME, E.WORKDEPT, YEAR (CURRENT_DATE - E.HIREDATE) AS WORKING_DAYS
  FROM EMPLOYEE E
  WHERE E.EMPNO = inputNumber;

SELECT YEAR (CURRENT_DATE - E.HIREDATE) AS WORKDATE FROM EMPLOYEE E;
SELECT * FROM TABLE (FN_45546_GETP('000010')) T;


SET SCHEMA FN45546;
CREATE TABLE EMPLOYEE LIKE EMPLOYEE;
INSERT INTO EMPLOYEE SELECT * FROM EMPLOYEE;
ALTER TABLE EMPLOYEE ADD PRIMARY KEY ();